version: '3'
services:
  app:
    build: ./weather-webapp/
    env_file:
      - ./weather-webapp/.env
    ports:
      - "3000:80"
  server:
    build: ./weather-service
    env_file:
      - ./weather-service/.env
    ports:
      - "5200:5200"      
