export const SET_STATE = 'SET_STATE';

//Organization Repos
export const SET_DAY_FORECAST_DATA = 'SET_DAY_FORECAST_DATA';
export const FETCH_DAY_FORECAST_DATA_FAIL = 'FETCH_DAY_FORECAST_DATA_FAIL';
export const GET_DAY_FORECAST_DATA = 'GET_DAY_FORECAST_DATA';
export const GET_DAY_FORECAST_DATA_START = 'GET_DAY_FORECAST_DATA_START';

//Hanlde restar
export const RESTART_DAY_FORECAST_DATA = 'RESTART_DAY_FORECAST_DATA';
export const RESTART_HOUR_FORECAST_DATA = 'RESTART_HOUR_FORECAST_DATA'

//Repo Commits
export const SET_HOUR_FORECAST_DATA = 'SET_HOUR_FORECAST_DATA';
export const FETCH_HOUR_FORECAST_DATA_FAIL = 'FETCH_HOUR_FORECAST_DATA_FAIL';
export const GET_HOUR_FORECAST_DATA = 'GET_HOUR_FORECAST_DATA';
export const GET_HOUR_FORECAST_DATA_START = 'GET_HOUR_FORECAST_DATA_START';

//Form
export const HANDLE_CITY_NAME_CHANGE = 'HANDLE_CITY_NAME_CHANGE';
export const HANDLE_DAY_NAME_CHANGE = 'HANDLE_DAY_NAME_CHANGE';
export const RESTART_FORM = 'RESTART_FORM';
export const RESTART_CLICK = 'RESTART_CLICK';
export const SEARCH_CLICK = 'SEARCH_CLICK';
